# Generated by Django 2.1.5 on 2019-01-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('timestamp', models.IntegerField()),
                ('sentiment_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
