# Generated by Django 2.1.5 on 2019-03-18 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='starred_user',
            field=models.ManyToManyField(related_name='starred_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
