# Generated by Django 2.1.5 on 2019-01-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sentiment_score',
            field=models.FloatField(blank=True),
        ),
    ]
