# Generated by Django 2.1.5 on 2019-01-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_articles', '0002_auto_20190119_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='order_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
